### ISSUE TITLE
I can probably help

### ISSUE THREAD

**Issue by Sarius997** [ndachel/PD-ice#1]
I wanted to ask, what's your aim to improve and add in your PD version, because I really like PD and its mods and wanted to know if I can help you somehow.
I also can help to test the application on an android emulator and on my Samsung Galaxy S3 mini.

PS.: Sorry for sending this as an issue, but I found no other way to get into contact with you

**Comment by ndachel** [comment]
Hi!
No problem sending this as an issue. Really, I have just wanted to learn some android game development, and I enjoy PD and wanted to hack on it some. The general idea was to try and make a new adventure for PD fans.(lofty goal) I wanted it to be partially outdoors, new monsters, new quests, new behaviors. So I have been working on it for 2 days (not much) So far I have been able to get it to build, re-skinned the tiles and intro screens, but that is about it. Are you aware of other mods out there? If so I would like to see them. You can contact me at ndachel@gmail.com and we can discuss more.
Thanks,
Nels.
